package com.legendapl.lightning.adhoc.calculate.field;

public interface LexicalType {

	public static final int AND = 100;
	public static final int OR = 101;
	public static final int MULTIS = 102;
	public static final int PLUS = 103;
	public static final int MINUS = 104;
	public static final int DIVIDE = 105;
	public static final int LEFT_PAREN = 106;
	public static final int RT_PAREN = 107;
	public static final int EQ = 108;
	public static final int GTR = 109;
	public static final int LESS = 110;
	public static final int LESS_EQ = 111;
	public static final int GTR_EQ = 112;
	public static final int NOT_EQ = 113;
	public static final int COLON = 114;
	public static final int FIELDNAME = 115;
	public static final int INT = 116;
	public static final int REAL = 117;
	public static final int CHARS = 118;
	public static final int ILLEGAL = 119;
	public static final int IsNull = 120;
	public static final int Absolute = 121;
	public static final int DayName = 122;
	public static final int DayNumber = 123;
	public static final int MonthName = 124;
	public static final int MonthNumber = 125;
	public static final int Year = 126;
	public static final int Length = 127;
	public static final int Round = 128;
	public static final int ElapsedDays = 129;
	public static final int ElapsedWeeks = 130;
	public static final int ElapsedMonths = 131;
	public static final int ElapsedQuarters = 132;
	public static final int ElapsedSemis = 133;
	public static final int ElapsedYears = 134;
	public static final int ElapsedHours = 135;
	public static final int ElapsedMinutes = 136;
	public static final int ElapsedSeconds = 137;
	public static final int Contains = 138;
	public static final int EndsWith = 139;
	public static final int StartsWith = 140;
	public static final int Concatenate = 141;
	public static final int Mid = 142;
	public static final int IF = 143;
	public static final int DateType = 144;
	public static final int TimestampType = 145;
	public static final int TimeType = 146;
	public static final int IntegerType = 147;
	public static final int DecimalType = 148;
	public static final int BooleanType = 149;
	public static final int Today = 150;
	public static final int TRUE = 151;
	public static final int FALSE = 152;
	public static final int COMMA = 153;
	public static final int NOT = 154;
	public static final int IN = 155;
	public static final int PECENT = 156;

}
